#!groovy
@Library('devops-library')
import bcgov.GitHubHelper

def BE_COV_STASH = 'backend-coverage'
def FE_COV_STASH = 'frontend-coverage'

def SONAR_ROUTE_NAME = 'sonarqube'
def SONAR_ROUTE_NAMESPACE = 'pbuo5q-tools'
def SONAR_PROJECT_NAME = 'UMU'
def SONAR_PROJECT_KEY = 'UMU'
def SONAR_PROJECT_BASE_DIR = '../'
def SONAR_SOURCES = './'
def SONARQUBE_URL = 'https://sonarqube-pbuo5q-tools.pathfinder.gov.bc.ca/projects'

pipeline{
    agent any

    tools {nodejs "nodejs"}

    environment{
        DEBUG_OUTPUT = 'false'

        DEV_PROJECT = 'pbuo5q-dev'
        TEST_PROJECT = 'pbuo5q-test'
        PROD_PROJECT = 'pbuo5q-prod'
        TOOLS_PROJECT = 'pbuo5q-tools'

        REPO_NAME = 'educ-umu'

        //with multiple developers, these variables should be dynamic to allow for multiple builds within the same OpenShift namespace
        OWNER = 'ndenny1'
        JOB_NAME = 'demo'

        APP_NAME = 'obiee-umu'
        APP_DOMAIN = 'pathfinder.gov.bc.ca'

        
        SOURCE_REPO_RAW = 'https://github.com/${OWNER}/${REPO_NAME}/master'
        SOURCE_REPO_REF = 'master'
        SOURCE_REPO_URL = 'https://github.com/${OWNER}/${REPO_NAME}.git'

        TOOLS_HOST_ROUTE = "${APP_NAME}-${TOOLS_PROJECT}.${APP_DOMAIN}"
        DEV_HOST_ROUTE = "${APP_NAME}-${DEV_PROJECT}.${APP_DOMAIN}"
        TEST_HOST_ROUTE = "${APP_NAME}-${TEST_PROJECT}.${APP_DOMAIN}"
        PROD_HOST_ROUTE = "${APP_NAME}-${PROD_PROJECT}.${APP_DOMAIN}"
    }

    stages {
        stage('Initialize') {
            agent any
            steps {
                // Cancel any running builds in progress
                timeout(10) {
                    echo "Cancelling previous ${APP_NAME}-${JOB_NAME} builds in progress..."
                    abortAllPreviousBuildInProgress(currentBuild)
                }

                script {
                    if(DEBUG_OUTPUT.equalsIgnoreCase('true')) {
                        // Force OpenShift Plugin directives to be verbose
                        openshift.logLevel(1)

                        // Print all environment variables
                        echo 'DEBUG - All pipeline environment variables:'
                        echo sh(returnStdout: true, script: 'env')
                    }
                }
            }
        }/*
        stage('Unit Tests') {
            agent any
            steps {
                script {
                    parallel(
                        Backend: {
                            dir('backend'){
                                try{
                                    timeout(10){
                                        echo 'Running backend lint checks and tests...'
                                        sh 'npm install'
                                        sh 'npm run lint:fix'
                                        sh 'npm run test'
                                        echo 'Backend lint checks and tests passed!'
                                        echo 'Reporting results...'
                                        junit 'tests/unit/reports/*.xml'
                                    }
                                } catch (e) {
                                    echo 'Backend lint checks and tests failed'
                                    throw e
                                }
                            }
                        },
                        Frontend: {
                            dir('frontend'){
                                try{
                                    timeout(10){
                                        echo 'Running frontend lint checks and tests...'
                                        sh 'npm install'
                                        sh 'npm run lint:fix'
                                        sh 'npm run test:unit'
                                        echo 'Frontend lint checks and tests passed!'
                                        echo 'Reporting results...'
                                        junit 'tests/unit/reports/*.xml'
                                    }
                                } catch (e) {
                                    echo 'Frontend lint checks and tests failed'
                                    throw e
                                }
                            }
                        }
                    )
                }
            }
            post {
                success {
                    stash name: BE_COV_STASH , includes: 'backend/coverage/**'
                    stash name: FE_COV_STASH, includes: 'frontend/coverage/**'

                    echo 'All lint checks and tests passed!'
                }
                failure {
                    echo 'Some lint checks and tests failed :('
                }
            }
        }*/
        stage('Build') {
            agent any
            steps{
                script {
                    openshift.withCluster(){
                        openshift.withProject(TOOLS_PROJECT){
                            parallel(
                                Backend: {
                                    try{
                                        def bcBackend = openshift.process('-f', 'openshift/obiee-backend.bc.yaml', "REPO_NAME=${REPO_NAME}", "JOB_NAME=${JOB_NAME}", "SOURCE_REPO_URL=${SOURCE_REPO_URL}", "SOURCE_REPO_REF=${SOURCE_REPO_REF}")

                                        openshift.apply(bcBackend).narrow('bc').startBuild('-w').logs('-f')

                                        openshift.tag("${REPO_NAME}-backend:latest", "${REPO_NAME}-backend:${JOB_NAME}")
                                    }
                                    catch(e) {
                                        echo "Backend build failed"
                                        throw e
                                    }
                                },
                                Frontend: {
                                    try{
                                        //notifyStageStatus('Frontend', 'PENDING')

                                        //define buildConfig
                                        def bcFrontend = openshift.process('-f', 'openshift/obiee-frontend.bc.yaml', "REPO_NAME=${REPO_NAME}", "JOB_NAME=${JOB_NAME}", "SOURCE_REPO_URL=${SOURCE_REPO_URL}", "SOURCE_REPO_REF=${SOURCE_REPO_REF}")
                                        
                                        //build from template and tag
                                        openshift.apply(bcFrontend).narrow('bc').startBuild('-w').logs('-f')
                                        openshift.tag("${REPO_NAME}-frontend:latest", "${REPO_NAME}-frontend:${JOB_NAME}")

                                        //define buildconfig for server
                                        def bcFrontendStatic = openshift.process('-f', 'openshift/obiee-frontend-static.bc.yaml', "REPO_NAME=${REPO_NAME}", "JOB_NAME=${JOB_NAME}", "NAMESPACE=${TOOLS_PROJECT}")

                                        //build from template and tag
                                        openshift.apply(bcFrontendStatic).narrow('bc').startBuild('-w').logs('-f')
                                        openshift.tag("${REPO_NAME}-frontend-static:latest", "${REPO_NAME}-frontend-static:${JOB_NAME}")

                                        //notifyStageStatus("Frontend", "SUCCESS")
                                    }
                                    catch(e){
                                        echo "Frontend build failed"
                                        //notifyStageStatus('Frontend', 'FAILURE')
                                        throw e
                                    }
                            },
                        )
                        }
                    }
                }
            }
            post{
                success {
                    echo 'Cleanup BuildConfigs...'
                    script {
                        openshift.withCluster() {
                        openshift.withProject(TOOLS_PROJECT) {
                            if(DEBUG_OUTPUT.equalsIgnoreCase('true')) {
                                echo "DEBUG - Using project: ${openshift.project()}"
                            } else {
                                def bcBackend = openshift.selector('bc', "${REPO_NAME}-backend-${JOB_NAME}")
                                def bcFrontend = openshift.selector('bc', "${REPO_NAME}-frontend-${JOB_NAME}")
                                def bcFrontendStatic = openshift.selector('bc', "${REPO_NAME}-frontend-static-${JOB_NAME}")

                                if(bcBackend.exists()){
                                    echo "Removing BuildConfig ${REPO_NAME}-backend-${JOB_NAME}..."
                                    bcBackend.delete()
                                }
                                if(bcFrontend.exists()) {
                                    echo "Removing BuildConfig ${REPO_NAME}-frontend-${JOB_NAME}..."
                                    bcFrontend.delete()
                                }
                                if(bcFrontendStatic.exists()) {
                                    echo "Removing BuildConfig ${REPO_NAME}-frontend-static-${JOB_NAME}..."
                                    bcFrontendStatic.delete()
                                }
                            }
                            }
                        }
                    }
                }
                failure {
                    echo 'Build stage failed'
                }
            }
        }
        stage('Deploy - Dev'){
            agent any
            steps{
                script {
                    deployStage('Dev', DEV_PROJECT, DEV_HOST_ROUTE)
                }
            }
            post{
                success{
                    echo 'Deployment to Dev was successful'
                }
                failure{
                    echo 'Deployment to Dev failed'
                }
            }
        }/*
        stage('e2e Tests'){
            steps{
                script{
                    openshift.withCluster() {
                        openshift.withProject() {
                            echo "Triggering e2e tests..."
                            def e2e = openshift.selector("bc", "e2e-tests")
                            e2e.startBuild()
                        }
                    }
                }
            }
        }*//*
        stage('SonarQube scan') {
            steps{
                script{
                    openshift.withCluster() {
                        openshift.withProject() {
                            unstash BE_COV_STASH
                            unstash FE_COV_STASH
                            echo "Triggering SonarQube analysis..."
                            def sonar = openshift.selector("bc", "sonarqube-scanner")
                            sonar.startBuild()
                        }
                    }
                }
            }
        }
        stage('Zap Scan'){
            steps{
                script{
                    openshift.withCluster() {
                        openshift.withProject() {
                            echo "Triggering ZAP pipeline..."
                            def zapScan = openshift.selector("bc", "owasp-zap-scanner")
                            zapScan.startBuild()
                        }
                    }
                }
            }
        }*/
        stage('Deploy - Test'){
            agent any
            steps{
                script{
                    deployStage('Test', TEST_PROJECT, TEST_HOST_ROUTE)
                }
            }
            post{
                success{
                    echo 'Succesfully deployed to Test environment'
                }
                failure{
                    echo 'Unable to deploy to Test environment'

                }
            }
        }
    }
}

def deployStage(String stageEnv, String projectEnv, String hostRouteEnv) {
  /*if (!stageEnv.equalsIgnoreCase('Dev')) {
    input("Deploy to ${projectEnv}?")
  }*/

  //notifyStageStatus("Deploy - ${stageEnv}", 'PENDING')

  openshift.withCluster() {
    openshift.withProject(projectEnv) {
      if(DEBUG_OUTPUT.equalsIgnoreCase('true')) {
        echo "DEBUG - Using project: ${openshift.project()}"
      }
      echo "Tagging Image ${REPO_NAME}-backend:${JOB_NAME}..."
      openshift.tag("${TOOLS_PROJECT}/${REPO_NAME}-backend:${JOB_NAME}", "${REPO_NAME}-backend:${JOB_NAME}")

      echo "Tagging Image ${REPO_NAME}-frontend-static:${JOB_NAME}..."
      openshift.tag("${TOOLS_PROJECT}/${REPO_NAME}-frontend-static:${JOB_NAME}", "${REPO_NAME}-frontend-static:${JOB_NAME}")

      echo "Processing DeploymentConfig ${REPO_NAME}-backend..."
      def dcBackendTemplate = openshift.process('-f',
        'openshift/obiee-backend.dc.yaml',
        "REPO_NAME=${REPO_NAME}",
        "JOB_NAME=${JOB_NAME}",
        "NAMESPACE=${projectEnv}",
        "APP_NAME=${APP_NAME}",
        "HOST_ROUTE=${hostRouteEnv}"
      )

      echo "Processing DeploymentConfig ${REPO_NAME}-frontend-static..."
      def dcFrontendStaticTemplate = openshift.process('-f',
        'openshift/obiee-frontend-static.dc.yaml',
        "REPO_NAME=${REPO_NAME}",
        "JOB_NAME=${JOB_NAME}",
        "NAMESPACE=${projectEnv}",
        "APP_NAME=${APP_NAME}",
        "HOST_ROUTE=${hostRouteEnv}"
      )

      //createDeploymentStatus(projectEnv, 'PENDING', hostRouteEnv)
      echo "Applying Deployment ${REPO_NAME}-backend..."
      def dcBackend = openshift.apply(dcBackendTemplate).narrow('dc')

      echo "Applying Deployment ${REPO_NAME}-frontend-static..."
      def dcFrontendStatic = openshift.apply(dcFrontendStaticTemplate).narrow('dc')

      // Wait for deployments to roll out
      timeout(10) {
        parallel(
            Backend: {
                dcBackend.rollout().status('--watch=true')
            },
            Frontend: {
                dcFrontendStatic.rollout().status('--watch=true')
            }
        )
      }
    }
  }
}

def notifyStageStatus(String name, String status) {
  def sha1 = GIT_COMMIT
  if(JOB_BASE_NAME.startsWith('PR-')) {
    sha1 = GitHubHelper.getPullRequestLastCommitId(this)
  }

  GitHubHelper.createCommitStatus(
    this, sha1, status, BUILD_URL, '', "Stage: ${name}"
  )
}

def createDeploymentStatus(String environment, String status, String hostUrl) {
  def ghDeploymentId = new GitHubHelper().createDeployment(
    this,
    SOURCE_REPO_REF,
    [
      'environment': environment,
      'task': "deploy:master"
    ]
  )

  new GitHubHelper().createDeploymentStatus(
    this,
    ghDeploymentId,
    status,
    ['targetUrl': "https://${hostUrl}"]
  )

  if (status.equalsIgnoreCase('SUCCESS')) {
    echo "${environment} deployment successful at https://${hostUrl}"
  } else if (status.equalsIgnoreCase('PENDING')) {
    echo "${environment} deployment pending..."
  } else if (status.equalsIgnoreCase('FAILURE')) {
    echo "${environment} deployment failed"
  }
}
