def appName = 'obiee-example'
pipeline {
  agent any
  stages {
    stage('preamble') {
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject() {
                        echo "Using project: ${openshift.project()}"
                    }
                }
            }
        }
    }
    stage('cleanup') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                        openshift.selector("all", [ template : appName ]).delete() 
                        if (openshift.selector("secrets", appName).exists()) { 
                            openshift.selector("secrets", appName).delete()
                        }
                    }
                }
            }
        }
    }
    stage('build') {
      steps {
        script {
            openshift.withCluster() {
                openshift.withProject() {
                  def builds = openshift.selector("bc", appName).related('builds')
                  timeout(5) { 
                    builds.untilEach(1) {
                      return (it.object().status.phase == "Complete")
                    }
                  }
                }
            }
        }
      }
    }
    stage('deploy') {
      steps {
        script {
            openshift.withCluster() {
                openshift.withProject() {
                  def rm = openshift.selector("dc", appName).rollout().latest()
                  timeout(5) { 
                    openshift.selector("dc", appName).related('pods').untilEach(1) {
                      return (it.object().status.phase == "Running")
                    }
                  }
                }
            }
        }
      }
    }
    /* Added comment to test merging */
    stage('promote_to_dev') {
      steps {
        script {
            git([url: "https://github.com/bcgov/EDUC-UMU", branch: 'dev'])
            sh 'git checkout dev'
            sh 'git merge tools'
            sh 'git commit -am "Merged tools branch to dev branch"'
            sh "git push master"
        }
      }
    }
  }
}